apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "photo-upload.fullname" . }}-config
  labels:
    {{- include "photo-upload.labels" . | nindent 4 }}
data:
  database.host: {{ include "photo-upload.database.host" . | quote }}
  database.port: {{ include "photo-upload.database.port" . | quote }}
  database.name: {{ include "photo-upload.database.name" . | quote }}
