apiVersion: v1
kind: Secret
metadata:
  name: {{ include "photo-upload.fullname" . }}-secret
  labels:
    {{- include "photo-upload.labels" . | nindent 4 }}
type: Opaque
data:
  database.user: {{ .Values.database.external.user | b64enc | quote }}
  database.password: {{ .Values.database.external.password | b64enc | quote }}
